/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/

#include <iostream>
#include <string>
#include <cmath>
#include <ctype.h>
#include <map>
using namespace std;

class Solution 
{
public:
    char findTheDifference(string s, string t) 
    {
		char result = 0;
		for(long i = 0; i < (long) s.size(); i++)
		{
			result = result ^ s[i];
		}
		for(long i = 0; i < (long) t.size(); i++)
		{
			result = result ^ t[i];
		}
		return result;
    }
};

int main()
{
	Solution ob;
	string input1 = "adbc";
	string input2 = "abcde";
 	char output = ob.findTheDifference(input1, input2);
	cout << output << endl;
	return 0;
}
